[build]
  publish = "frontend"
  command = "echo 'Static frontend build (Backend must be hosted elsewhere)'"

[[redirects]]
  from = "/api/*"
  to = "https://money-muling-detection-backend.onrender.com/api/:splat"
  status = 200
  force = true
